# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillctl < Formula
  desc "Interactive TUI for managing curated AI skills across agent folders"
  homepage "https://github.com/akl773/skillctl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akl773/skillctl/releases/download/v0.1.0/skillctl_darwin_amd64.tar.gz"
      sha256 "e8039874bfaabaf75f0c8e0bec2d5790ecb4c4d32c47ba72c1cfe2efac434d6a"

      define_method(:install) do
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akl773/skillctl/releases/download/v0.1.0/skillctl_darwin_arm64.tar.gz"
      sha256 "e65a359ee40e1bce418c61c371b61501b6b9a894a576ab980b0bdd4d2d1beaad"

      define_method(:install) do
        bin.install "skillctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akl773/skillctl/releases/download/v0.1.0/skillctl_linux_amd64.tar.gz"
      sha256 "bee52894d478773aa027ea0b7096110217d1062d30a7aa6a401c2bb01542a628"
      define_method(:install) do
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akl773/skillctl/releases/download/v0.1.0/skillctl_linux_arm64.tar.gz"
      sha256 "54d6e78005acfc60424e0e511b2e7cbf7f1cb88de73948483ce242b81ca41ba4"
      define_method(:install) do
        bin.install "skillctl"
      end
    end
  end

  test do
    system "#{bin}/skillctl", "--version"
  end
end
