# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillctl < Formula
  desc "Interactive TUI for managing curated AI skills across agent folders"
  homepage "https://github.com/akl773/skillctl"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akl773/skillctl/releases/download/v0.1.5/skillctl_darwin_amd64.tar.gz"
      sha256 "ca8e1c512360704e4cbcb0910d072b2070bee6e8777a5c7688ecff76d2778363"

      define_method(:install) do
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akl773/skillctl/releases/download/v0.1.5/skillctl_darwin_arm64.tar.gz"
      sha256 "0a57ad62caf4daeb96d3b8f9cf64bb86ad5d059f34176667c0134437c92c586a"

      define_method(:install) do
        bin.install "skillctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akl773/skillctl/releases/download/v0.1.5/skillctl_linux_amd64.tar.gz"
      sha256 "2e2b1d3998703e8b3c8cf15953ecf1b01d8f83f0af832ca13a17d990188c6c52"
      define_method(:install) do
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akl773/skillctl/releases/download/v0.1.5/skillctl_linux_arm64.tar.gz"
      sha256 "9b4c49cc9d4044f09ee8c28e6b163bbfba63434f74788da045b121d5ebd268ee"
      define_method(:install) do
        bin.install "skillctl"
      end
    end
  end

  test do
    system "#{bin}/skillctl", "--version"
  end
end
